name: Build the mod for Linux, Windows, and MacOS
on:
    workflow_dispatch

jobs:
    build-natives:
        runs-on: ${{ matrix.runner }}
        strategy:
            matrix:
                runner: [ubuntu-latest, macos-latest, windows-latest]
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            # Install dependencies
            - name: Install dependencies (Linux)
              if: runner.os == 'Linux'
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential cmake pkg-config libasound2-dev libpulse-dev
            
            
            - name: Install dependencies (MacOS)
              if: runner.os == 'macOS'
              run: |
                brew update
                brew install cmake pkg-config
            
            - name: Setup MSYS2 (Windows)
              if: runner.os == 'Windows'
              uses: msys2/setup-msys2@v2
              with:
                msystem: MINGW64
                update: true

            - name: Install packages via MSYS2 (Windows)
              if: runner.os == 'Windows'
              shell: msys2 {0}
              run: |
                pacman -S --noconfirm --needed git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-pkg-config
            
            - name: Setup CMake helper (cross-platform)
              uses: jwlawson/actions-setup-cmake@v2
            
            - name: Configure and set up espeak-ng (Windows)
              if: runner.os == 'Windows'
              shell: msys2 {0}
              run: |
                git clone --depth 1 https://github.com/espeak-ng/espeak-ng.git
                cd espeak-ng
                cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
                cmake --build build --config Release -- -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || 2)
                cmake --install build --prefix ./install
            
            - name: Configure and set up espeak-ng (Linux/macOS)
              if: runner.os != 'Windows'
              run: |
                git clone --depth 1 https://github.com/espeak-ng/espeak-ng.git
                cd espeak-ng

                # TODO: Consider leaving out -DBUILD_SHARED_LIBS=ON and building cross-platform static library files? (.a)
                cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
                cmake --build build --config Release -- -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || 2)
                cmake --install build --prefix ./install

            # Find espeak-ng
            - name: Finding the built out espeak-ng lib
              id: findlib
              shell: bash
              run: |
                cd espeak-ng
                BASE_LIB="install/lib/espeak-ng"
                case "$(uname -s)" in
                    Linux*)  LIB="$BASE_LIB/libespeak-ng.so" ;;
                    Darwin*) LIB="$BASE_LIB/libespeak-ng.dylib" ;;
                    MINGW*|MSYS*|CYGWIN*) LIB="$BASE_LIB/espeak-ng.dll" ;;
                    *) LIB="" ;;
                esac

                echo "-- $BASE_LIB/lib:"
                ls $BASE_LIB/lib

                echo "-- $BASE_LIB/bin:"
                ls $BASE_LIB/bin

                echo "-- $BASE_LIB/share:"
                ls $BASE_LIB/share

                if [ ! -f "$LIB" ]; then
                    echo "libespeak.* not found at expected path: $LIB"
                    exit 1
                fi
                
                echo "found=$LIB"
                echo "found=$LIB" >> $GITHUB_OUTPUT
            
            - name: Upload espeak-ng native library
              uses: actions/upload-artifact@v4
              with:
                name: natives-${{ runner.os }}
                path: ${{ steps.findlib.outputs.found }}
            
            - name: Upload espeak-ng data folder
              if: runner.os == 'Linux'
              uses: actions/upload-artifact@v4
              with:
                name: espeak-ng-data
                path: espeak-ng/espeak-ng-data/**
        
    build:
        runs-on: ubuntu-latest
        needs: build-natives
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Clean up native folder in case there are existing files in the repo
              run: |
                mkdir -p src/client/resources/native
                rm -f src/client/resources/native/*.dll
                rm -f src/client/resources/native/*.so
                rm -f src/client/resources/native/*.dylib
            
            - name: Download all native artifacts
              uses: actions/download-artifact@v4
              with:
                path: natives

            - name: Merge natives into project
              run: |
                find natives -type f ! -path "*/espeak-ng-data/*" -exec cp {} src/client/resources/native/ \;
                cp -r natives/espeak-ng-data/* src/client/resources/native/espeak-ng-data/

            - name: List native folder for debugging
              run: ls -R src/client/resources/native
            
            - name: Make Gradle wrapper executable (grrr Linux grrrrrr)
              run: chmod +x ./gradlew

            - name: Building jar
              run: ./gradlew assemble --no-daemon
            
            - name: Filter out the *.sources.jars
              run: |
                mkdir -p out
                for f in build/libs/*.jar; do
                    if [[ "$f" != *-sources.jar ]]; then
                        mv "$f" out/
                    fi
                done
            
            # Uploading ttvoice to artifacts
            - name: Upload ttvoice to artifacts
              if: success()
              uses: actions/upload-artifact@v4
              with:
                name: release
                path: out/*.jar
